# Generated by Django 4.1.3 on 2022-11-04 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Drivetrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_from', models.IntegerField()),
                ('mileage_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('main_photo', models.ImageField(upload_to='media')),
                ('other_photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('city', models.CharField(choices=[(1, 'Rivne')], max_length=50)),
                ('run', models.IntegerField()),
                ('accidents', models.BooleanField(default=False)),
                ('description_accidents', models.TextField(max_length=300)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_exchange_app.bodytype')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_exchange_app.color')),
                ('drivetrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_exchange_app.drivetrain')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_exchange_app.mark')),
                ('renge_mileage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_exchange_app.mileage')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_exchange_app.transmission')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_exchange_app.year')),
            ],
        ),
    ]
