# Generated by Django 4.1.3 on 2022-11-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='car_exchange_app.answer', verbose_name='answers'),
        ),
    ]
