# Generated by Django 4.1.3 on 2022-11-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0002_category_subcategory_remove_car_body_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='car_exchange_app.category'),
        ),
    ]
