# Generated by Django 4.1.3 on 2022-11-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0003_remove_car_category_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default='2022-11-11 19:51:09'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(default='2022-11-11 19:51:09'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(related_name='cars', to='car_exchange_app.category'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default='2022-11-11 19:51:09'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(default='2022-11-11 19:51:09'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default='2022-11-11 19:51:09'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default='2022-11-11 19:51:09'),
        ),
    ]
