# Generated by Django 4.1.3 on 2022-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0003_remove_answer_answer_answer_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
