# Generated by Django 4.1.3 on 2022-11-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0005_remove_answer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_exchange_app.answer', verbose_name='Answer'),
        ),
    ]
