# Generated by Django 4.1.3 on 2022-11-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0005_alter_answer_created_at_alter_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateField(default='2022-11-11'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateField(default='2022-11-11'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateField(default='2022-11-11'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateField(default='2022-11-11'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(default='2022-11-11'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateField(default='2022-11-11'),
        ),
    ]
