# Generated by Django 4.1.3 on 2022-11-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0006_message_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default='2022-11-16:14:39:49'),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(default='2022-11-16:14:39:49'),
        ),
    ]
