# Generated by Django 4.1.3 on 2022-11-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0007_message_created_at_message_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default='2022-11-16|14:40:20'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(default='2022-11-16|14:40:20'),
        ),
    ]
