# Generated by Django 4.1.3 on 2022-11-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0011_remove_message_user_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_exchange_app.answer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_exchange_app.question'),
        ),
    ]
