# Generated by Django 4.1.3 on 2022-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_exchange_app', '0012_alter_message_answer_alter_message_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='car_in_the_preferences',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='car_exchange_app.car'),
        ),
    ]
